version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./fastapi_template:/web/fastapi_template
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0